/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * add2Room.java
 *
 * Created on 11 Μαρ 2010, 1:25:14 μμ
 */

package GUI;
import Basics.* ;
import DBConnection.DB;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bettina
 */
public class add2Room extends javax.swing.JFrame {
    int RoomNumberV;
    double Cost=100;
    String temp=null;
    Global g;
    


    /** Creates new form add2Room */
    public add2Room( Global g ) {
        this.g =g;


        //System.out.println("TO kostos einai :" + x + "Kai to roomNumber einai :" + RN);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SaveButoon = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        CostComboBox = new javax.swing.JComboBox();
        CancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RoomNumberTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add New Double Room");

        jLabel2.setText("Cost per Customer");

        SaveButoon.setText("Save");
        SaveButoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerfomed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CostComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100", "120", "140", "160", "180", "200", " " }));
        CostComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostComboBoxActionPerfomed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Room Number");

        RoomNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNumberTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel1)
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveButoon)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(395, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RoomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(SaveButoon)
                    .addComponent(CancelButton))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_CancelButtonActionPerformed

    private void RoomNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomNumberTextFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
         new addPlace(g).setVisible(true);
         this.dispose();
         
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SaveButtonActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerfomed
        // TODO add your handling code here:
        // Akrivws idia ulopoisi me tin add2Rooms
       


         boolean roomNumberFlag = true;
         temp = RoomNumberTextField.getText();
         try{
                     RoomNumberV = Integer.parseInt(temp);
                     DB data = new DB();
                     boolean flag =data.CheckRoom(RoomNumberV);

                     if ( flag)
                     {

                         try
                         {
                              data.InsertRoom(RoomNumberV, 2, Cost, "room", "no");
                              JOptionPane.showMessageDialog(this,"SUCCESFULL ADD ROOM : " +RoomNumberV);

                         }
                         catch ( Exception e)
                         {
                                System.out.println("Error");
                         }

                     }
                     else
                          JOptionPane.showMessageDialog(this,"WRONG ROOMUMBER INPUT ");
                     

/*

                     if ( roomNumberFlag)
                     {

                          JOptionPane.showMessageDialog(this,"SUCCESFULL ADD ROOM : " +RoomNumberV);

                          StandardRoom r = new StandardRoom(RoomNumberV,2,Cost,"n","room");

                          g.rooms.add(r);
                          this.dispose();
                     }
 */

         }
         catch(Exception exe)
         {
             JOptionPane.showMessageDialog(this,"WRONG ROOMUMBER INPUT ");
         }
         

 

                 
         

          
        
          
        
    }//GEN-LAST:event_SaveButtonActionPerfomed

    private void CostComboBoxActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostComboBoxActionPerfomed
        // TODO add your handling code here:


        String temp = (String)CostComboBox.getSelectedItem();
        Cost  = Double.parseDouble(temp);

    }//GEN-LAST:event_CostComboBoxActionPerfomed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox CostComboBox;
    private javax.swing.JTextField RoomNumberTextField;
    private javax.swing.JButton SaveButoon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
