/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * add3Room.java
 *
 * Created on 11 Μαρ 2010, 1:58:51 μμ
 */

package GUI;

import Basics.StandardRoom;
import javax.swing.JOptionPane;

/**
 *
 * @author bettina
 */
public class add3Room extends javax.swing.JFrame {

    int RoomNumberV;
    double Cost=220;
    String temp;
    Global g;


    /** Creates new form add3Room */
    public add3Room( Global g) {
        this.g = g;
        initComponents( );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CostComboBox = new javax.swing.JComboBox();
        SaveButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RoomNumberTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add New Triple Room");

        jLabel2.setText("Cost per Customer");

        CostComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "220", "240", "260", "280", "300", " " }));
        CostComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostActionPerfomed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonAP(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Room Number");

        RoomNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNumberTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(256, 256, 256))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(327, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveButton)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(CancelButton)
                    .addComponent(SaveButton))
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RoomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_CancelButtonActionPerformed

    private void RoomNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomNumberTextFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:

        boolean roomNumberFlag = true;
         temp = RoomNumberTextField.getText();// diabazei apo ton xrhsth to roonNumber. An den mporei na to kanei integer exoume mnm lathous
         try{
                     RoomNumberV = Integer.parseInt(temp);//an uparxei hdh exoume mhm lathous
                     for ( int i = 0 ; i<g.rooms.size();i++)
                         {
                             if ( g.rooms.get(i).getRoomnumber() == RoomNumberV)
                             {
                                 JOptionPane.showMessageDialog(this,"ROOMNUMBER :" +RoomNumberV + " ALREADY EXISTS ");
                                 roomNumberFlag = false;
                                 break;

                             }
                         }



                     if ( roomNumberFlag)// an den uparxei to ftiaxnei kai to eisagei sthn lista
                     {

                          JOptionPane.showMessageDialog(this,"SUCCESFULL ADD ROOM : " +RoomNumberV);

                          StandardRoom r = new StandardRoom(RoomNumberV,3,Cost,"n","room");

                          g.rooms.add(r);
                          this.dispose();
                     }

         }
         catch(Exception exe)
         {
             JOptionPane.showMessageDialog(this,"WRONG ROOMUMBER INPUT ");
         }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CostActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostActionPerfomed
        // TODO add your handling code here:

        String temp = (String)CostComboBox.getSelectedItem();
        Cost  = Double.parseDouble(temp);
    }//GEN-LAST:event_CostActionPerfomed

    private void BackButtonAP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonAP
        // TODO add your handling code here:
        new addPlace(g).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonAP

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox CostComboBox;
    private javax.swing.JTextField RoomNumberTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
