/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addPlace.java
 *
 * Created on 10 Μαρ 2010, 9:30:00 μμ
 */

package GUI;

import java.util.ArrayList;
import Basics.*;

/**
 *
 * @author bettina
 */
public class addPlace extends javax.swing.JFrame {
    Global g;

 

       /** Creates new form addPlace */
    public addPlace( Global g) {
        this.g = g;
        
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupChoice = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nextB = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        DoubleButton = new javax.swing.JRadioButton();
        SuiteButton = new javax.swing.JRadioButton();
        TripleButton = new javax.swing.JRadioButton();
        cancelB = new javax.swing.JButton();
        HallButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("addPlace");

        jLabel1.setText("Add New Place");

        nextB.setText("Next");
        nextB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextClicked(evt);
            }
        });
        nextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBActionPerformed(evt);
            }
        });

        jLabel4.setText("Type Of Room");

        groupChoice.add(DoubleButton);
        DoubleButton.setText("Double");
        DoubleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleButtonActionPerformed(evt);
            }
        });

        groupChoice.add(SuiteButton);
        SuiteButton.setText("Suite");

        groupChoice.add(TripleButton);
        TripleButton.setText("Triple");
        TripleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TripleButtonActionPerformed(evt);
            }
        });

        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        groupChoice.add(HallButton);
        HallButton.setText("Hall");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45)
                                .addComponent(DoubleButton)
                                .addGap(18, 18, 18)
                                .addComponent(TripleButton)
                                .addGap(18, 18, 18)
                                .addComponent(SuiteButton))
                            .addComponent(cancelB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextB)
                            .addComponent(HallButton))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DoubleButton)
                    .addComponent(TripleButton)
                    .addComponent(SuiteButton)
                    .addComponent(HallButton))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextB)
                    .addComponent(cancelB))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    private void TripleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TripleButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TripleButtonActionPerformed

    private void DoubleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_DoubleButtonActionPerformed

    private void nextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBActionPerformed
      //new add2Room().setVisible(true);
        
    }//GEN-LAST:event_nextBActionPerformed

    private void nextClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextClicked
        if (DoubleButton.isSelected())
            new add2Room(g).setVisible(true);
        else if (TripleButton.isSelected())
            new add3Room(g).setVisible(true);
        else if (SuiteButton.isSelected())
            new addSuite(g).setVisible(true);
        else if (HallButton.isSelected())
            new addHall(g).setVisible(true);


        this.dispose();
    }//GEN-LAST:event_nextClicked

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JRadioButton DoubleButton;
    private javax.swing.JRadioButton HallButton;
    private javax.swing.JRadioButton SuiteButton;
    private javax.swing.JRadioButton TripleButton;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton cancelB;
    private javax.swing.ButtonGroup groupChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton nextB;
    // End of variables declaration//GEN-END:variables

}
