/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * earningStatistics1.java
 *
 * Created on 13 Μαρ 2010, 2:53:32 μμ
 */

package GUI;

import Basics.ControlGui;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author bettina
 */
public class earningStatistics1 extends javax.swing.JFrame {
    
    GregorianCalendar Start = new GregorianCalendar();
    GregorianCalendar End = new GregorianCalendar();
    Global g;


    /** Creates new form earningStatistics1 */
    public earningStatistics1(Global g) {
        this.g =g;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StartDate = new javax.swing.JSpinner();
        End_Date = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("View Earning Statistics");

        jLabel2.setText("Select Date:");

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jLabel3.setText("From:");

        jLabel4.setText("To:");

        StartDate.setModel(new javax.swing.SpinnerDateModel());

        End_Date.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(67, 67, 67))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cancel)
                                        .addGap(18, 18, 18)
                                        .addComponent(Search))
                                    .addComponent(End_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(113, 113, 113)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(End_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Search))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:

        Date date_in = new Date();
        date_in = (Date) StartDate.getValue();
        Start.setTime(date_in);// diabazei tis imerominies apo to jspinner kai tis pernaei stis metablites
                                // start kai End


        Date date_out = new Date();
        date_out = (Date) End_Date.getValue();
        End.setTime(date_out);
        
        double Total_earning=0;

        for ( int i =0;i<g.roomReservation.size();i++)
        {
            if(ControlGui.substractDays(g.roomReservation.get(i).getDate_out(), Start) > 0)// an mia kratisi dwmatiou ligei mesa sto xroniko diastima
                if(ControlGui.substractDays(g.roomReservation.get(i).getDate_out(), End) < 0)// Start - End prosthetei to kostos tis kratisis sto TotalCost
                    Total_earning += g.roomReservation.get(i).getTotalCost();

        }
        
        
        for ( int i =0;i<g.hallReservationsT.size();i++)
        {
            if(ControlGui.substractDays(g.hallReservationsT.get(i).getDate_in(), Start) > 0)// omoiws kai gia ta hall Reservation
                if(ControlGui.substractDays(g.hallReservationsT.get(i).getDate_in(), End) < 0)
                    Total_earning += g.roomReservation.get(i).getTotalCost();

        }


            if ( Total_earning == 0)
                 JOptionPane.showMessageDialog(this,"NO EXPECTED EARNINGS FOR THE CHOSEN DATES");//tupwsei to apotelesma!!
            else
                JOptionPane.showMessageDialog(this,"THE EXPECTED EARNINGS FOR THE CHOSEN DATES ARE : " + Total_earning);//tupwsei to apotelesma!!

        



    }//GEN-LAST:event_SearchActionPerformed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JSpinner End_Date;
    private javax.swing.JButton Search;
    private javax.swing.JSpinner StartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
