/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * companyReservation.java
 *
 * Created on 11 Μαρ 2010, 12:08:45 πμ
 */

package GUI;

import Basics.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import java.awt.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author bettina
 */
public class HallReservationGui extends javax.swing.JFrame {

    Global g;
    String CompanyN;
    String Fiscal;
    int NumOfHalls = 1;
    int NumOfSeats = 20;
    GregorianCalendar DATE_IN = new GregorianCalendar();
    GregorianCalendar DATE_OUT = new GregorianCalendar();
    boolean soft_drink ,full_meal,light_meal;
     public DefaultListModel dlm;

    String temp;

    /** Creates new form companyReservation */
    public HallReservationGui(Global g) {
        this.g = g;
         //dimiourgia tou dlmModel gia tin epexergasia tis listas
         dlm = new DefaultListModel();
         int count =0;
         //emfanizei sti lista oles tis diathesimes aithouses
        for( int i = 0;i<g.halls.size();i++)
        {
            if((g.halls.get(i).reserved.equals("n") )  )
            {
                    dlm.add(count,g.halls.get(i));
                    count++;
            }
        }

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CompanyNameField = new javax.swing.JTextField();
        FiscalCodeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        StartDate = new javax.swing.JSpinner();
        EndDate = new javax.swing.JSpinner();
        CancelButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        LightMealButton = new javax.swing.JRadioButton();
        FullMealButton = new javax.swing.JRadioButton();
        SoftDrinksButton = new javax.swing.JRadioButton();
        NumSeats = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        HallsList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setText("Create New Reservation for Company");

        jLabel2.setText("Company's Name");

        jLabel3.setText("Fiscal Code");

        jLabel5.setText("Start Date");

        jLabel6.setText("End Date");

        jLabel7.setText("Number of Seats");

        StartDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1273524000000L), new java.util.Date(1273524000000L), new java.util.Date(2094064800000L), java.util.Calendar.DAY_OF_MONTH));

        EndDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(2094064800000L), java.util.Calendar.DAY_OF_MONTH));

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Check the boxes below if you want any of these Extras:");

        buttonGroup1.add(LightMealButton);
        LightMealButton.setText("Light meal");
        LightMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LightMealButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(FullMealButton);
        FullMealButton.setText("Full meal");
        FullMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullMealButtonActionPerformed(evt);
            }
        });

        SoftDrinksButton.setText("Soft drinks");
        SoftDrinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoftDrinksButtonActionPerformed(evt);
            }
        });

        NumSeats.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "50", "100", "150", "200", "300", "400", "500", "700" }));
        NumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumSeatsActionPerformed(evt);
            }
        });

        HallsList.setModel(dlm);
        jScrollPane1.setViewportView(HallsList);

        jLabel4.setText("Available Halls");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addContainerGap(642, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CancelButton)
                                    .addComponent(SoftDrinksButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SaveButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LightMealButton)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FullMealButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EndDate, 0, 0, Short.MAX_VALUE)
                                    .addComponent(FiscalCodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(CompanyNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(StartDate, 0, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(108, 108, 108))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 551, Short.MAX_VALUE)))))
                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CompanyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(FiscalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(NumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoftDrinksButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LightMealButton)
                    .addComponent(FullMealButton))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(SaveButton))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
         
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
         {
         light_meal = false;
         full_meal = false;
         soft_drink = false;

         //sillogi dedomenon apo ti forma
         CompanyN = CompanyNameField.getText();
         Fiscal = FiscalCodeField.getText();
         
         Date date_in = new Date();
         date_in = (Date) StartDate.getValue();
         DATE_IN.setTime(date_in);


         Date date_out = new Date();
         date_out = (Date) EndDate.getValue();
         DATE_OUT.setTime(date_out);

         if( LightMealButton.isSelected())
             light_meal = true;

         if( FullMealButton.isSelected())
             full_meal = true;

         if( SoftDrinksButton.isSelected())
             soft_drink = true;

         try
         {
         //periptoseis lathous eisagosis stoixeion apo to xristi
         if (CompanyN.equals("") || Fiscal.equals(""))
         {
           JOptionPane.showMessageDialog(this,"NO NAME OR ID");//keno onoma i ID
         }
         else
         {
                   //dimiourgia antikeimenou
                   HallReservation HR = Basics.ControlGui.readHallReservation(CompanyN, Fiscal,
                                    NumOfSeats, DATE_IN,g.halls,soft_drink,full_meal,light_meal);

                    if(HR.getCompanyName().equals(""))//den iparxoun diathesimes aithouses
                    {
                        JOptionPane.showMessageDialog(this,"HALL RESERVATION *ERROR* \nNOT AVAILABLE HALLS");
                    }
                    else//orthi eisagogi antikeimenou sti lista hallReservation
                    {
                             g.hallReservationsT.add(HR);
                             JOptionPane.showMessageDialog(this,"HALL RESERVATION  SUCCESFULL\n TOTAL COST OF RESERVATION : "
                                     +HR. getTotalCost() +"\n CUSTOMERS NAME : " + HR.getCompanyName());
                             this.dispose();
                    }
         }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"HALL RESERVATION ERROR");
            this.dispose();

        }
        }

    }//GEN-LAST:event_SaveButtonActionPerformed

    private void LightMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LightMealButtonActionPerformed
      
    }//GEN-LAST:event_LightMealButtonActionPerformed

    private void FullMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullMealButtonActionPerformed
        
    }//GEN-LAST:event_FullMealButtonActionPerformed

    private void SoftDrinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoftDrinksButtonActionPerformed
       
    }//GEN-LAST:event_SoftDrinksButtonActionPerformed

    private void NumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumSeatsActionPerformed
        //metatropi
        temp = (String)NumSeats.getSelectedItem();
        NumOfSeats = Integer.parseInt(temp);
    }//GEN-LAST:event_NumSeatsActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField CompanyNameField;
    private javax.swing.JSpinner EndDate;
    private javax.swing.JTextField FiscalCodeField;
    private javax.swing.JRadioButton FullMealButton;
    private javax.swing.JList HallsList;
    private javax.swing.JRadioButton LightMealButton;
    private javax.swing.JComboBox NumSeats;
    private javax.swing.JButton SaveButton;
    private javax.swing.JRadioButton SoftDrinksButton;
    private javax.swing.JSpinner StartDate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
