/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newReservation.java
 *
 * Created on 11 Μαρ 2010, 12:01:55 πμ
 */

package GUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bettina
 */
public class newReservation extends javax.swing.JFrame {
    Global g;

    /** Creates new form newReservation */
    public newReservation(Global g) {

        this.g = g;

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        CompanyButton = new javax.swing.JRadioButton();
        CustomerButtonSuite = new javax.swing.JRadioButton();
        NextButton = new javax.swing.JButton();
        CustomerButtonRoom = new javax.swing.JRadioButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Create New Reservation");

        buttonGroup1.add(CompanyButton);
        CompanyButton.setText("Hall");

        buttonGroup1.add(CustomerButtonSuite);
        CustomerButtonSuite.setText("Suite");
        CustomerButtonSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerButtonSuiteActionPerformed(evt);
            }
        });

        NextButton.setText("Next");
        NextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nexClicked(evt);
            }
        });
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(CustomerButtonRoom);
        CustomerButtonRoom.setText("Room");
        CustomerButtonRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerButtonRoomActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(CompanyButton)
                        .addGap(38, 38, 38)
                        .addComponent(CustomerButtonSuite)
                        .addGap(34, 34, 34)
                        .addComponent(CustomerButtonRoom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addComponent(NextButton)
                .addGap(426, 426, 426))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyButton)
                    .addComponent(CustomerButtonSuite)
                    .addComponent(CustomerButtonRoom))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(NextButton))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nexClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nexClicked
        

    }//GEN-LAST:event_nexClicked

    private void CustomerButtonSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerButtonSuiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerButtonSuiteActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        if (CompanyButton.isSelected())
            new HallReservationGui(g).setVisible(true);
        else if (CustomerButtonSuite.isSelected())
            new SuiteReservationGui(g).setVisible(true);
        else if (CustomerButtonRoom.isSelected())
            new RoomReservationGui(g).setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_NextButtonActionPerformed

    private void CustomerButtonRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerButtonRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerButtonRoomActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton CompanyButton;
    private javax.swing.JRadioButton CustomerButtonRoom;
    private javax.swing.JRadioButton CustomerButtonSuite;
    private javax.swing.JButton NextButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
