/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * customerReservation.java
 *
 * Created on 11 Μαρ 2010, 12:27:40 πμ
 */

package GUI;

import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import Basics.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bettina
 */
public class RoomReservationGui extends javax.swing.JFrame {

    int NumOfRooms =1;
    int NumOfCustomers = 2;
    String name,id;
    Global g;
    GregorianCalendar DATE_IN = new GregorianCalendar();
    GregorianCalendar DATE_OUT = new GregorianCalendar();

    public DefaultListModel dlm;

    /** Creates new form customerReservation */
    public RoomReservationGui(Global g) {
        this.g =g;

         //dimiourgia tou dlmModel gia tin epexergasia tis listas
         dlm = new DefaultListModel();
         int count =0;

          //emfanizei sti lista oles tis diathesimes souites
         for( int i = 0;i<g.rooms.size();i++)
         {
            if((g.rooms.get(i).reserved.equals("n") ) &&
                    (g.rooms.get(i).type.equals("room")) )
            {
                    dlm.add(count,g.rooms.get(i));
                    count++;
            }
        }

         
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        StartDate = new javax.swing.JSpinner();
        End_Date = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        NumRooms = new javax.swing.JComboBox();
        NumCustomers = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomsList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Create New Reservation for Customer");

        jLabel2.setText("Name");

        jLabel4.setText("Identification number");

        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });

        jLabel5.setText("Number of Rooms");

        jLabel6.setText("Start Date");

        jLabel7.setText("End Date");

        StartDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1273313700000L), new java.util.Date(1273313700000L), new java.util.Date(1703978100000L), java.util.Calendar.DAY_OF_MONTH));
        StartDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                StartDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        StartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StartDateKeyPressed(evt);
            }
        });

        End_Date.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1268260510599L), new java.util.Date(1331418900000L), java.util.Calendar.DAY_OF_MONTH));

        jLabel8.setText("Number of customers");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        NumRooms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        NumRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumRoomsActionPerformed(evt);
            }
        });

        NumCustomers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3" }));
        NumCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCustomersActionPerformed(evt);
            }
        });

        RoomsList.setModel(dlm);
        jScrollPane1.setViewportView(RoomsList);

        jLabel3.setText("Available Rooms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinner3, 0, 0, Short.MAX_VALUE)
                                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(End_Date, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                        .addComponent(StartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SaveButton)))))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(NumRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(End_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NumCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(CancelButton))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_StartDateAncestorAdded
      

    }//GEN-LAST:event_StartDateAncestorAdded

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed


        //sillogi dedomenon apo ti forma
        name = Name.getText();
        id = Id.getText();
        
        Date date_in = new Date();
        date_in = (Date) StartDate.getValue();
        DATE_IN.setTime(date_in);


        Date date_out = new Date();
        date_out = (Date) End_Date.getValue();
        DATE_OUT.setTime(date_out);


        
        try
        {
        //periptoseis lathous eisagosis stoixeion apo to xristi
         if( ControlGui.substractDays(DATE_IN,DATE_OUT) > 0)
         {
                    JOptionPane.showMessageDialog(this,"ERROR DATES");//lathos kataxorimenes imerominies
         }
         else if (name.equals("") || id.equals(""))
         {
           JOptionPane.showMessageDialog(this,"NO NAME OR ID");  //keno onoma i ID
         }
         else
         {

         //dimiourgia antikeimenou
         StandardRoomReservation SRR = Basics.ControlGui.readRoomReservation(name, id,
                            NumOfRooms,NumOfCustomers,
                            DATE_IN, DATE_OUT,g.rooms);

                    if(SRR.getName().equals(""))
                    {
                        JOptionPane.showMessageDialog(this,"ROOM RESERVATION *ERROR* " +
                                "\nNOT AVAILABLE ROOMS");//den iparxoun diathesima domatia
                    }
                    else//orthi eisagogi antikeimenou sti lista roomReservation
                    {
                             g.roomReservation.add(SRR);
                             JOptionPane.showMessageDialog(this," ROOM RESERVATION SUCCESFULL ");
                             this.dispose();
                    }
         }
   

        
}catch(Exception e)
{
    JOptionPane.showMessageDialog(this,"ROOM RESERVATION ERROR \n" );
    this.dispose();

}
        





    }//GEN-LAST:event_SaveButtonActionPerformed

    private void StartDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StartDateKeyPressed
      
    }//GEN-LAST:event_StartDateKeyPressed

    private void NumCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCustomersActionPerformed
        //metatropi
        String temp = (String)NumCustomers.getSelectedItem();
        NumOfCustomers  = Integer.parseInt(temp);
    }//GEN-LAST:event_NumCustomersActionPerformed

    private void NumRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumRoomsActionPerformed
       //metatropi
       String temp = (String)NumRooms.getSelectedItem();
       NumOfRooms  = Integer.parseInt(temp);
    }//GEN-LAST:event_NumRoomsActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:

         this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JSpinner End_Date;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox NumCustomers;
    private javax.swing.JComboBox NumRooms;
    private javax.swing.JList RoomsList;
    private javax.swing.JButton SaveButton;
    private javax.swing.JSpinner StartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    // End of variables declaration//GEN-END:variables

}
