/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * customerReservationSuite.java
 *
 * Created on 7 Μαϊ 2010, 8:41:24 μμ
 */

package GUI;

import Basics.ControlGui;
import Basics.SuiteReservation;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bettina
 */
public class SuiteReservationGui extends javax.swing.JFrame {

    Global g;
    String Name;
    String Id;
    int NumOfSuites = 1;
    int NumOfCustomers = 2;
    GregorianCalendar DATE_IN = new GregorianCalendar();
    GregorianCalendar DATE_OUT = new GregorianCalendar();
    boolean pool,jacuzi,internet,tv;
    public DefaultListModel dlm;

    String temp;

    /** Creates new form companyReservation */
    public SuiteReservationGui(Global g) {
        this.g = g;

        //dimiourgia tou dlmModel gia tin epexergasia tis listas
        dlm = new DefaultListModel();
        int count =0;

         //emfanizei sti lista ola ta diathesima domatia
        for( int i = 0;i<g.rooms.size();i++)
        {
            if((g.rooms.get(i).reserved.equals("n") ) &&
                    (g.rooms.get(i).type.equals("suite")) )
            {
                    dlm.add(count,g.rooms.get(i));
                    count++;
            }
        }

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        IdField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Pool = new javax.swing.JCheckBox();
        Jacuzzi = new javax.swing.JCheckBox();
        Internet = new javax.swing.JCheckBox();
        Tv = new javax.swing.JCheckBox();
        RoomNum = new javax.swing.JComboBox();
        numCustomer = new javax.swing.JComboBox();
        StartDate = new javax.swing.JSpinner();
        EndDate = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        SuiteList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Create New Reservation for Customer");

        jLabel2.setText("Name");

        jLabel4.setText("Identification number");

        jLabel5.setText("Number of Suites");

        jLabel6.setText("Start Date");

        jLabel7.setText("End Date");

        jLabel8.setText("Number of customers");

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Check the boxes below if you want any of these Extras:");

        Pool.setText("Pool");

        Jacuzzi.setText("Jacuzzi");

        Internet.setText("Internet");

        Tv.setText("Extra tv");

        RoomNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        RoomNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNumActionPerformed(evt);
            }
        });

        numCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        numCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCustomerActionPerformed(evt);
            }
        });

        StartDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1273352460000L), new java.util.Date(1273352460000L), new java.util.Date(1652475660000L), java.util.Calendar.DAY_OF_MONTH));
        StartDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                StartDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        EndDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1273352460000L), new java.util.Date(1273352460000L), new java.util.Date(1589576460000L), java.util.Calendar.DAY_OF_MONTH));
        EndDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                EndDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        SuiteList.setModel(dlm);
        SuiteList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SuiteListAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(SuiteList);

        jLabel3.setText("Available Suites");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Pool)
                                .addComponent(Internet)
                                .addComponent(Jacuzzi)
                                .addComponent(Tv))
                            .addContainerGap(366, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(CancelButton)
                            .addGap(18, 18, 18)
                            .addComponent(SaveButton)
                            .addGap(46, 46, 46))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(numCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(263, 263, 263))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(IdField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                                            .addGap(79, 79, 79))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(RoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(263, 263, 263))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(StartDate, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(EndDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, Short.MAX_VALUE))
                                            .addGap(133, 133, 133)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(numCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pool))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jacuzzi)
                        .addGap(13, 13, 13)
                        .addComponent(Internet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(Tv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(CancelButton))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RoomNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNumActionPerformed
        // metatropi
         temp = (String)RoomNum.getSelectedItem();
        NumOfSuites  = Integer.parseInt(temp);
    }//GEN-LAST:event_RoomNumActionPerformed

    private void numCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCustomerActionPerformed
        //metatropi
        temp = (String)numCustomer.getSelectedItem();
        NumOfCustomers  = Integer.parseInt(temp);
    }//GEN-LAST:event_numCustomerActionPerformed

    private void StartDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_StartDateAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDateAncestorAdded

    private void EndDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_EndDateAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_EndDateAncestorAdded

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

        pool =false;internet =false;
        jacuzi =false;tv=false;
        
        //sillogi dedomenon apo ti forma
        Name = NameField.getText();
        Id = IdField.getText();

        Date date_in = new Date();
        date_in = (Date) StartDate.getValue();
        DATE_IN.setTime(date_in);


        Date date_out = new Date();
        date_out = (Date) EndDate.getValue();
        DATE_OUT.setTime(date_out);

        if( Pool.isSelected())
            pool = true;

        if( Internet.isSelected())
            internet = true;

        if( Jacuzzi.isSelected())
            jacuzi = true;

        if( Tv.isSelected())
            tv = true;

        try
        {
                //periptoseis lathous eisagosis stoixeion apo to xristi
                 if( ControlGui.substractDays(DATE_IN,DATE_OUT) > 0)
                 {
                            JOptionPane.showMessageDialog(this,"ERROR DATES");//lathos kataxorimenes imerominies
                 }
                 else if (Name.equals("") || Id.equals(""))
                 {
                   JOptionPane.showMessageDialog(this,"NO NAME OR ID");//lathos onoma i ID
                 }
                 else
                 {
                     //anazitisi ston pinaka rooms gia tis suites pou einai diathesimes
                     for( int i =0;i<g.rooms.size();i++)
                     {
                         if(g.rooms.get(i).type.equals("suite")&& g.rooms.get(i).reserved.equals("n"))
                            System.out.println( g.rooms.get(i).getRoomnumber()+ " "
                                 + g.rooms.get(i).getBednumber());
                     }
                                //dimiourgia antikeimenou
                                SuiteReservation SR = Basics.ControlGui.readSuiteReservation( Name, Id,
                                NumOfSuites,NumOfCustomers,DATE_IN,DATE_OUT,g.rooms,
                                        pool , internet,jacuzi,tv);
                                

                    if(SR.getName().equals(""))//periptosi eisagogis kenou onomatos sti forma
                    {
                        JOptionPane.showMessageDialog(this,"SUITE RESERVATION *ERROR*" +
                                "\n NOT AVAILABLE SUITES");
                    }
                    else
                    {
                        //orthi eisagogi antikeimenou sti lista roomReservation
                        g.roomReservation.add(SR);
                        JOptionPane.showMessageDialog(this,"SUITE RESERVATION  SUCCESFULL");
                         this.dispose();
                         
                    }
                 }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"SUITE RESERVATION ERROR");
            this.dispose();

        }

    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SuiteListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SuiteListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_SuiteListAncestorAdded
    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JSpinner EndDate;
    private javax.swing.JTextField IdField;
    private javax.swing.JCheckBox Internet;
    private javax.swing.JCheckBox Jacuzzi;
    private javax.swing.JTextField NameField;
    private javax.swing.JCheckBox Pool;
    private javax.swing.JComboBox RoomNum;
    private javax.swing.JButton SaveButton;
    private javax.swing.JSpinner StartDate;
    private javax.swing.JList SuiteList;
    private javax.swing.JCheckBox Tv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox numCustomer;
    // End of variables declaration//GEN-END:variables

}
