/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateSuite.java
 *
 * Created on 10 Μαϊ 2010, 7:39:50 μμ
 */

package GUI;

import Basics.StandardRoom;
import Basics.Suite;
import javax.swing.JOptionPane;

/**
 *
 * @author bettina
 */
public class UpdateSuite extends javax.swing.JFrame {
    Global g;
    Suite s;
    double Cost;
    String temp;
    int RoomNumberV;
    int NumOfBeds;
    String RoomNum;

    boolean roomNumberFlag;

    /** Creates new form Update2Room */
    public UpdateSuite(Global g,Suite s ) {
        this.g = g;
        this.s = s;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayNumRoom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SaveButoon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CostComboBox = new javax.swing.JComboBox();
        BackButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NumOfBedsCB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DisplayNumRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayNumRoomActionPerformed(evt);
            }
        });

        jLabel3.setText("Suite Number");

        SaveButoon.setText("Save");
        SaveButoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButoonSaveButtonActionPerfomed(evt);
            }
        });

        jLabel2.setText("Cost per Customer");

        CostComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100", "120", "140", "160", "180", "200", " " }));
        CostComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostComboBoxActionPerfomed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Update Data for Suite");

        jLabel4.setText("Number of Beds");

        NumOfBedsCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", " " }));
        NumOfBedsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumOfBedsCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(350, Short.MAX_VALUE)
                                .addComponent(BackButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumOfBedsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DisplayNumRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveButoon)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DisplayNumRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumOfBedsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(SaveButoon)
                    .addComponent(CancelButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayNumRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayNumRoomActionPerformed

}//GEN-LAST:event_DisplayNumRoomActionPerformed

    private void SaveButoonSaveButtonActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButoonSaveButtonActionPerfomed
        try {

            temp = DisplayNumRoom.getText();
            RoomNumberV = Integer.parseInt(temp);
            roomNumberFlag = true;

            for ( int i = 0 ; i<g.rooms.size();i++)
                if ( g.rooms.get(i).getRoomnumber() == s.getRoomnumber())
                    g.rooms.remove(g.rooms.get(i));


            for ( int i = 0 ; i<g.rooms.size();i++) {
                if ( g.rooms.get(i).getRoomnumber() == RoomNumberV) {
                    JOptionPane.showMessageDialog(this,"ROOMNUMBER :"
                            +RoomNumberV + " ALREADY EXISTS ");
                    roomNumberFlag = false;
                    break;

                }
            }


            if ( roomNumberFlag) {

                JOptionPane.showMessageDialog(this,"UPDATE SUITE SUCCESFULL");

                StandardRoom r = new StandardRoom(RoomNumberV,NumOfBeds,Cost,"n","room");

                g.rooms.add(r);
                this.dispose();
            }


        }catch( Exception e) {
            JOptionPane.showMessageDialog(this," WRONG SUITE NUMBER INPUT");
        }
    }//GEN-LAST:event_SaveButoonSaveButtonActionPerfomed

    private void CostComboBoxActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostComboBoxActionPerfomed
        String temp1;
        temp1 = (String)CostComboBox.getSelectedItem();
        Cost  = Double.parseDouble(temp1);
}//GEN-LAST:event_CostComboBoxActionPerfomed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new addPlace(g).setVisible(true);
        this.dispose();
}//GEN-LAST:event_BackButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_CancelButtonActionPerformed

    private void NumOfBedsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumOfBedsCBActionPerformed
        // TODO add your handling code here:
        String temp = (String)NumOfBedsCB.getSelectedItem();
        NumOfBeds  = Integer.parseInt(temp);
}//GEN-LAST:event_NumOfBedsCBActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox CostComboBox;
    private javax.swing.JTextField DisplayNumRoom;
    private javax.swing.JComboBox NumOfBedsCB;
    private javax.swing.JButton SaveButoon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
