/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateRoom.java
 *
 * Created on 8 Μαϊ 2010, 11:48:56 μμ
 */

package GUI;

import Basics.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author bettina
 */
public class UpdateRoom extends javax.swing.JFrame {

    Global g;
    String S;
    public DefaultListModel dlm;

    /** Creates new form UpdateRoom */
    public UpdateRoom(Global g,String S) {
        this.g=g;
        this.S =S;

        //dimiourgia tou dlmModel gia tin epexergasia tis listas
        dlm = new DefaultListModel();
        int count =0;

        //apo ton constructor tis UpdateRoom exoume perasei os orisma ena string
        //pou analoga me to ti exei epilexei o xristis apo ta RadioButtons tis proigoumenis formas
        //kanei tous aparaititous elegxous parakato

        //periptosi doubleRoom
        if (S.equals("double"))
        {

                for( int i = 0;i<g.rooms.size();i++)
                {
                    if(g.rooms.get(i).getBednumber() == 2 && g.rooms.get(i).type.equals("room"))
                    {
                            //provoli sti lista olon ton diklinon domation
                            dlm.add(count,g.rooms.get(i));
                            count++;
                    }
                }
                
        }
        
        
        if (S.equals("triple"))
        {

        
                System.out.println(S);
                for( int i = 0;i<g.rooms.size();i++)
                {
                    if(g.rooms.get(i).getBednumber() == 3 && g.rooms.get(i).type.equals("room") )
                    {
                        //provoli sti lista olon ton diklinon domation
                            dlm.add(count,g.rooms.get(i));
                            count++;
                    }
                }
                
        }


        if (S.equals("suite"))
        {

                System.out.println(S);
                for( int i = 0;i<g.rooms.size();i++)
                {
                    if( g.rooms.get(i).type.equals("suite") )
                    {
                        //provoli sti lista olon ton souiton
                            dlm.add(count,g.rooms.get(i));
                            count++;
                    }
                }

        }


        if (S.equals("hall"))
        {


                 for( int i = 0;i<g.halls.size();i++)
                 {
                     //provoli sti lista olon ton aithouson
                    dlm.add(count,g.halls.get(i));
                    count++;
                 }

        }

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Update");

        jLabel2.setText("Enter the Number of the room or hall you want to update");

        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");

        List.setModel(dlm);
        jScrollPane1.setViewportView(List);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1)
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(CancelButton)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(NextButton)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(BackButton)
                    .addComponent(NextButton))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
      this.dispose();
}//GEN-LAST:event_CancelButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
    //provoli tis antistoixis formas analoga tin epilogi tou domatiou
        if ( S.equals("double"))
        {
            StandardRoom SR = (StandardRoom)List.getSelectedValue();
            for(int i =0;i<g.rooms.size();i++)
                if(SR.getRoomnumber()==g.rooms.get(i).getRoomnumber())
                        new Update2Room(g,(StandardRoom)g.rooms.get(i)).setVisible(true);

            this.dispose();
        }

        if ( S.equals("triple"))
        {
            StandardRoom SR = (StandardRoom)List.getSelectedValue();
            for(int i =0;i<g.rooms.size();i++)
                if(SR.getRoomnumber()==g.rooms.get(i).getRoomnumber())
                        new Update3Room(g,(StandardRoom)g.rooms.get(i)).setVisible(true);

            this.dispose();
        }


        if ( S.equals("suite"))
        {
            Suite SR = (Suite)List.getSelectedValue();
            for(int i =0;i<g.rooms.size();i++)
                if(SR.getRoomnumber() == g.rooms.get(i).getRoomnumber())
                        new UpdateSuite(g,(Suite)g.rooms.get(i)).setVisible(true);

            this.dispose();
        }


        if ( S.equals("hall"))
        {
            Hall H = (Hall)List.getSelectedValue();
            for(int i =0;i<g.halls.size();i++)
                if(H.getHallnum()==g.halls.get(i).getHallnum())
                        new UpdateHall(g,(Hall)g.halls.get(i)).setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_NextButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JList List;
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
