/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateCustomerR.java
 *
 * Created on 9 Μαϊ 2010, 3:41:30 μμ
 */

package GUI;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import Basics.*;
import javax.swing.DefaultListModel;
/**
 *
 * @author bettina
 */
public class UpdateRoomReservation extends javax.swing.JFrame {

    Global g;
    String Id;
    boolean b =false;
    int NumOfRooms =1;
    int NumOfCustomers = 2;
    String name;
    GregorianCalendar DATE_IN = new GregorianCalendar();
    GregorianCalendar DATE_OUT = new GregorianCalendar();
    RoomReservation RR_temp;
     public DefaultListModel dlm;


    /** Creates new form UpdateCustomerR */
    public UpdateRoomReservation(Global g,RoomReservation RR_temp)
    {
        this.g = g;
        this.RR_temp =RR_temp;


         dlm = new DefaultListModel();
         int count =0;

        for( int i = 0;i<g.rooms.size();i++)// emfanizei ta diathesima dwmatia!!
        {
            if((g.rooms.get(i).reserved.equals("n") ) &&
                    (g.rooms.get(i).type.equals("room")) )
            {
                    dlm.add(count,g.rooms.get(i));
                    count++;
            }
        }

        
        //Text.append(RR.getId());
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumRooms = new javax.swing.JComboBox();
        StartDate = new javax.swing.JSpinner();
        EndDate = new javax.swing.JSpinner();
        NumCustomers = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RoomsList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumRooms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        NumRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumRoomsActionPerformed(evt);
            }
        });

        StartDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1273437804394L), new java.util.Date(1273437566812L), null, java.util.Calendar.DAY_OF_MONTH));
        StartDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                StartDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        EndDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1273437820170L), new java.util.Date(1273437577538L), null, java.util.Calendar.DAY_OF_MONTH));
        EndDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                EndDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        NumCustomers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        NumCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCustomersActionPerformed(evt);
            }
        });

        jLabel5.setText("Number of Rooms");

        jLabel6.setText("Start Date");

        jLabel7.setText("End Date");

        jLabel8.setText("Number of customers");

        jButton2.setText("Cancel");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Update reservation for Customer");

        jLabel2.setText("Name");

        jLabel3.setText("Identification Number");

        RoomsList.setModel(dlm);
        jScrollPane2.setViewportView(RoomsList);

        jLabel4.setText("Available Rooms");

        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(EndDate, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                        .addComponent(StartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(IDField, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                        .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                    .addGap(127, 127, 127)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaveButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel4)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(NumRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(NumCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(jButton2))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumRoomsActionPerformed
        String temp = (String)NumRooms.getSelectedItem();
        NumOfRooms  = Integer.parseInt(temp);
}//GEN-LAST:event_NumRoomsActionPerformed

    private void StartDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_StartDateAncestorAdded

    }//GEN-LAST:event_StartDateAncestorAdded

    private void EndDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_EndDateAncestorAdded
        // TODO add your handling code here:
}//GEN-LAST:event_EndDateAncestorAdded

    private void NumCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCustomersActionPerformed
        String temp = (String)NumCustomers.getSelectedItem();
        NumOfCustomers  = Integer.parseInt(temp);
}//GEN-LAST:event_NumCustomersActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed


        name = Name.getText();
        Id = IDField.getText();//diabazei ta kainouria stoixei apo ton xrhsth

        Date date_in = new Date();
        date_in = (Date) StartDate.getValue();
        DATE_IN.setTime(date_in);


        Date date_out = new Date();
        date_out = (Date) EndDate.getValue();
        DATE_OUT.setTime(date_out);

        if (name.equals("")  )// an ta pedia name kai id einai kena pairnei ws name kai id
           name = RR_temp.getName();// ta hdh uparxonta apo to antikeimeno pou tropopoioume
         else if(Id.equals("") )
             Id = RR_temp.getId();




try
{

         if( ControlGui.substractDays(DATE_IN,DATE_OUT) > 0)
         {// elegxos gia imerominies
                    JOptionPane.showMessageDialog(this,"ERROR DATES");
         }
         else
         {


         StandardRoomReservation SRR = Basics.ControlGui.readRoomReservation(name, Id,
                            NumOfRooms,NumOfCustomers,
                            DATE_IN, DATE_OUT,g.rooms);// ftiaxnei to kainourio antikeimeno

                    if(SRR.getName().equals(""))
                    {
                        JOptionPane.showMessageDialog(this,"UPDATE ROOM RESERVATION ERROR\n NOT AVAILABLE ROOMS");
                    }
                    else
                    {

                             for( int i=0;i<g.roomReservation.size();i++)
                                         if(RR_temp.getId().equals(g.roomReservation.get(i).getId() ) )
                                             g.roomReservation.remove(g.roomReservation .get(i));// diagrafei tin palia eggrafi apo ton pinaka


                             g.roomReservation.add(SRR);// eisagei tin kainouria eggrafi ston pinaka!
                             JOptionPane.showMessageDialog(this," UPDATE ROOM RESERVATION SUCCESFULL");
                             this.dispose();
                    }
         }



}catch(Exception e)
{
    JOptionPane.showMessageDialog(this,"UPDATE ROOM RESERVATION ERROR ");
    this.dispose();

}
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner EndDate;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox NumCustomers;
    private javax.swing.JComboBox NumRooms;
    private javax.swing.JList RoomsList;
    private javax.swing.JButton SaveButton;
    public javax.swing.JSpinner StartDate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
