/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Update2Room.java
 *
 * Created on 10 Μαϊ 2010, 4:18:02 μμ
 */

package GUI;

import Basics.StandardRoom;
import javax.swing.JOptionPane;

/**
 *
 * @author bettina
 */
public class Update2Room extends javax.swing.JFrame {

    Global g;
    double Cost;
    String temp;
    int RoomNumberV;
    String RoomNum;
    StandardRoom r;
    boolean roomNumberFlag;

    /** Creates new form Update2Room */
    public Update2Room(Global g,StandardRoom r ) {
        this.g = g;
        this.r = r;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CostComboBox = new javax.swing.JComboBox();
        BackButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        SaveButoon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DisplayNumRoom = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Update Data for Double Room");

        jLabel2.setText("Cost per Customer");

        CostComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100", "120", "140", "160", "180", "200", " " }));
        CostComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostComboBoxActionPerfomed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SaveButoon.setText("Save");
        SaveButoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButoonSaveButtonActionPerfomed(evt);
            }
        });

        jLabel3.setText("Room Number");

        DisplayNumRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayNumRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayNumRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(316, 316, 316))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(30, 30, 30)
                .addComponent(CancelButton)
                .addGap(37, 37, 37)
                .addComponent(SaveButoon)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DisplayNumRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CostComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(CancelButton)
                    .addComponent(SaveButoon))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CostComboBoxActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostComboBoxActionPerfomed
        String temp1;
        temp1 = (String)CostComboBox.getSelectedItem();
        Cost  = Double.parseDouble(temp1);
    }//GEN-LAST:event_CostComboBoxActionPerfomed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new addPlace(g).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButoonSaveButtonActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButoonSaveButtonActionPerfomed
        try {

             temp = DisplayNumRoom.getText();
             RoomNumberV = Integer.parseInt(temp);
             roomNumberFlag = true;

            //anazitisi tis thesis pou to stoixeio RoomNumber einai to idio me auto
            //pou simplirose o xristis sti forma
            //sti sinexeia diagrafi tou antikeimenou apo ti lista
            for ( int i = 0 ; i<g.rooms.size();i++)
             if ( g.rooms.get(i).getRoomnumber() == r.getRoomnumber())
                 g.rooms.remove(g.rooms.get(i));
             
              //anazitisi sti lista rooms se periptosi eisagogis
              //arithmou domatiou pou iparxei idi
              for ( int i = 0 ; i<g.rooms.size();i++)
                {
                     if ( g.rooms.get(i).getRoomnumber() == RoomNumberV)
                     {
                         JOptionPane.showMessageDialog(this,"ROOMNUMBER :" +RoomNumberV
                                 +" ALREADY EXISTS ");
                         roomNumberFlag = false;
                         break;

                     }
                }

         //prosthiki enimeromenou antikeimenou sti lista rooms
         if ( roomNumberFlag)
         {

              JOptionPane.showMessageDialog(this,"UPDATE ROOM OK");

              r = new StandardRoom(RoomNumberV,2,Cost,"n","room");

              g.rooms.add(r);
              this.dispose();
         }
         

        }catch( Exception e) {
            JOptionPane.showMessageDialog(this," WRONG ROOM NUMBER INPUT");
        }

    }//GEN-LAST:event_SaveButoonSaveButtonActionPerfomed

    private void DisplayNumRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayNumRoomActionPerformed
        
    }//GEN-LAST:event_DisplayNumRoomActionPerformed

    /**
    * @param args the command line arguments
    */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox CostComboBox;
    private javax.swing.JTextField DisplayNumRoom;
    private javax.swing.JButton SaveButoon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
