/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdatePlace.java
 *
 * Created on 9 Μαϊ 2010, 3:23:39 μμ
 */

package GUI;

/**
 *
 * @author bettina
 */
public class UpdatePlace extends javax.swing.JFrame {

    Global g;
    /** Creates new form UpdatePlace */
    public UpdatePlace(Global g) {
        this.g=g;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DoubleButton = new javax.swing.JRadioButton();
        TripleButton = new javax.swing.JRadioButton();
        SuiteButton = new javax.swing.JRadioButton();
        HallButton = new javax.swing.JRadioButton();
        cancelB = new javax.swing.JButton();
        NextButton = new javax.swing.JToggleButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Update  Place");

        jLabel4.setText("Type Of Room");

        buttonGroup1.add(DoubleButton);
        DoubleButton.setText("Double");
        DoubleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(TripleButton);
        TripleButton.setText("Triple");
        TripleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TripleButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(SuiteButton);
        SuiteButton.setText("Suite");

        buttonGroup1.add(HallButton);
        HallButton.setText("Hall");

        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        NextButton.setText("Next");
        NextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextButtonnextClicked(evt);
            }
        });
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(165, 165, 165))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(DoubleButton)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(BackButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NextButton)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TripleButton)
                                .addGap(26, 26, 26)
                                .addComponent(SuiteButton)
                                .addGap(18, 18, 18)
                                .addComponent(HallButton)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DoubleButton)
                    .addComponent(SuiteButton)
                    .addComponent(TripleButton)
                    .addComponent(HallButton))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton)
                    .addComponent(cancelB)
                    .addComponent(BackButton))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoubleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_DoubleButtonActionPerformed

    private void TripleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TripleButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TripleButtonActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelBActionPerformed

    private void NextButtonnextClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextButtonnextClicked
        
}//GEN-LAST:event_NextButtonnextClicked

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        //diaxorizei tin epilogi tou xristi apo ta RadioButtons sti forma
        //gia na ton parapempsei stin epomeni
        String d ="double";
        String t ="triple";
        String s ="suite";
        String h ="hall";
        if(DoubleButton.isSelected())
            new UpdateRoom(g,d).setVisible(true);
        else if(TripleButton.isSelected())
            new UpdateRoom(g,t).setVisible(true);
        else if(SuiteButton.isSelected())
            new UpdateRoom(g,s).setVisible(true);
        else if(HallButton.isSelected())
            new UpdateRoom(g,h).setVisible(true);

        this.dispose();
    }//GEN-LAST:event_NextButtonActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    protected javax.swing.JRadioButton DoubleButton;
    private javax.swing.JRadioButton HallButton;
    private javax.swing.JToggleButton NextButton;
    private javax.swing.JRadioButton SuiteButton;
    private javax.swing.JRadioButton TripleButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
